<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Film extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $casts = [
        'genre' => 'array'
    ];

    function screenings()
    {
        return $this->hasMany(Screening::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $model->slug = Str::slug($model->title);
        });
    }
}
